#!/usr/bin/env python3
"""Generate repository indexes from blueprint, catalog, and implemented lab metadata."""

from __future__ import annotations

import argparse
from pathlib import Path

import yaml

from assessment_contract import DOMAIN_DISPLAY_NAMES


ROOT = Path(__file__).resolve().parents[1]


def load_yaml(path: Path):
    with path.open("r", encoding="utf-8") as handle:
        return yaml.safe_load(handle)


def objective_titles() -> dict[str, str]:
    blueprint = load_yaml(ROOT / "curriculum" / "blueprint.yml")
    titles = {
        item["id"]: item["title"]
        for item in blueprint.get("foundationObjectives", [])
    }
    for domain in blueprint.get("domains", []):
        for group in domain.get("groups", []):
            for item in group.get("objectives", []):
                titles[item["id"]] = item["title"]
    return titles


def render_question_index() -> str:
    titles = objective_titles()
    rows: list[str] = []
    domain_counts = {domain: 0 for domain in DOMAIN_DISPLAY_NAMES}
    for path in sorted((ROOT / "labs").glob("[0-9][0-9]-*/assessment/questions.yml")):
        questions = load_yaml(path)
        lab = path.parents[1].name
        lab_metadata = load_yaml(path.parents[1] / "lab.yml")
        domain = (lab_metadata.get("assessment") or {}).get("primaryDomain", "unknown")
        if domain in domain_counts:
            domain_counts[domain] += len(questions)
        for question in questions:
            objectives = ", ".join(question.get("objectiveIds", []))
            objective_names = "; ".join(titles.get(item, "Unknown objective") for item in question.get("objectiveIds", []))
            rows.append(
                f"| {question['id']} | `{lab}` | {DOMAIN_DISPLAY_NAMES.get(domain, domain)} | "
                f"{question['difficulty']} | {objectives} | {objective_names} | {question['lastVerified']} |"
            )
    table = "\n".join(rows) if rows else "| — | — | — | — | — | No assessments implemented | — |"
    summary = "\n".join(
        f"| {display_name} | {domain_counts[domain]} |"
        for domain, display_name in DOMAIN_DISPLAY_NAMES.items()
    )
    return f"""# Question bank index

This generated index intentionally omits correct answers. Open each lab's `assessment/ANSWERS.md` only after completing its questions.

| Official domain | Questions |
|---|---:|
{summary}

| Question | Lab | Official domain | Difficulty | Objective IDs | Objective topics | Verified |
|---|---|---|---|---|---|---|
{table}

Generated by `python tools/generate_indexes.py`. Do not edit by hand.
"""


def render_status_index() -> str:
    catalog = load_yaml(ROOT / "labs" / "catalog.yml")
    rows: list[str] = []
    for item in catalog.get("labs", []):
        folder = f"{item['id']}-{item['slug']}"
        lab_path = ROOT / "labs" / folder / "lab.yml"
        status = item.get("status", "planned")
        question_count = item.get("assessmentQuestionCount", 0)
        if lab_path.exists():
            lab = load_yaml(lab_path)
            status = lab.get("status", status)
            question_count = (lab.get("assessment") or {}).get("questionCount", question_count)
        rows.append(
            f"| {item['id']} | `{folder}` | {item['domain']} | {item['track']} | {status} | {question_count} |"
        )
    return f"""# Implementation status

| Lab | Folder | Domain | Track | Lab status | Questions |
|---:|---|---|---|---|---|
{chr(10).join(rows)}

Generated by `python tools/generate_indexes.py`. `offline-validated` confirms repository quality gates, not a live Azure deployment. Question counts come from each lab's assessment contract.
"""


def update(path: Path, content: str, check: bool) -> bool:
    existing = path.read_text(encoding="utf-8") if path.exists() else None
    if existing == content:
        print(f"PASS  {path.relative_to(ROOT)} is current")
        return True
    if check:
        print(f"FAIL  {path.relative_to(ROOT)} is stale; run python tools/generate_indexes.py")
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(content)
    print(f"WRITE {path.relative_to(ROOT)}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    results = [
        update(ROOT / "docs" / "question-bank-index.md", render_question_index(), args.check),
        update(ROOT / "docs" / "implementation-status.md", render_status_index(), args.check),
    ]
    return 0 if all(results) else 1


if __name__ == "__main__":
    raise SystemExit(main())
